name: envs build and model tests
# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
    
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: Install dependencies
              run: |
                  pip install torch
                  pip install numpy
            - name: Install local packages
              run: |
                  pip install -e.
            - name: Run trained model
              working-directory: ./tests
              run : |
                  python encoder_test.py
                  python decoder_test.py
